In [1]:
import numpy as np

X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.rand(100, 1)

In [2]:
'''利用numpy, 纯公式计算'''
# np.linalg.inv() 计算矩阵的逆
# dot() 方法 计算矩阵的内积
X_b = np.c_[np.ones((100, 1)), X] # add x0=1 to each instance
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
print(theta_best)

# make predictions using  θ^
X_new = np.array([[0], [2]])
X_new_b = np.c_[np.ones((2,1)), X_new] # add x0=1 to each instance
y_predict = X_new_b.dot(theta_best)
print(y_predict)

[[4.57547716]
 [2.9636076 ]]
[[ 4.57547716]
 [10.50269235]]


In [4]:
'''sklearn 版本'''
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)
print(lin_reg.intercept_, lin_reg.coef_)

# 预测 
X_new = np.array([[0], [2]])
print(lin_reg.predict(X_new))

[4.57547716] [[2.9636076]]
[[ 4.57547716]
 [10.50269235]]


In [6]:
'''tensorflow 版本'''
import tensorflow as tf

X_b = np.c_[np.ones((100, 1)), X] # add x0=1 to each instance
X_b_T = tf.transpose(X_b)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(X_b_T, X_b)), X_b_T), y)

# 预测
X_new = np.array([[0], [2]])
X_new_b = np.c_[np.ones((2,1)), X_new] # add x0=1 to each instance
y_predict = tf.matmul(X_new_b, theta)

with tf.Session() as sess:
    theta_val, y_predict_val = sess.run([theta, y_predict])
    print(theta_val)
    print(y_predict_val)

[[4.57547716]
 [2.9636076 ]]
[[ 4.57547716]
 [10.50269235]]
